version: "3"

networks:
  default:
    name: mba_ufrj

services:
  docs:
    container_name: docs
    image: swaggerapi/swagger-ui
    ports:
      - 8095:8095
    environment:
      SWAGGER_JSON: docs/swagger.json
    volumes:
      - ./docs/swagger.json:/docs/swagger.json

  api:
    container_name: backend
    build:
      context: ./
      dockerfile: api.Dockerfile
    ports:
      - 5000:5000

  # db:
  #   container_name: database
  #   image: mysql
  #   ports:
  #     - "3306:3306"
